# Teil 1: Optionen
include_dateien               = [ # wo wird nach .h Dateien gesucht?
'.'                               # im lokalen Verzeichnis
]
shared_libraries              = [ # mathematische Funktionen der Standardbibliothek
'm'
]
cpp_standard                  = [ # Angaben zum Standard
'-std=c++98',                     # ISO/IEC Standard 14882
'-pedantic'                       # keine Erweiterungen zulaessig
]
warnungen                     = [ # Einstellungen zu Fehlern
'-Wall',                          # viel meckern
'-Wextra',                        # extra viel meckern
'-Werror'                         # Warnungen sind Fehler
]

# Teil 2: Definition des Environments
std = Environment(
  CXXFLAGS = cpp_standard + warnungen,
  CPPPATH = include_dateien,
  LIBS = shared_libraries
)

# Teil 3: Programm bauen
cpp_dateien = [                   # hier C++-Dateien einfuegen
'namen_main.c++',              # Kommentar moeglich
'name.c++',                   # hier weitere C++-Dateien angeben
'datum.c++',
'eingaben.c++',
'menue.c++',
'zufallsgenerator.c++',
'person.c++',
'student.c++',
'beschaeftigter.c++',
'professor.c++',
'personengenerator.c++',
'land.c++',
'ort.c++',
'postanschrift.c++',
'dateimanager.c++',
'namensliste.c++',
'ortsliste.c++',
'beschreibbar.c++',
'semestersimulator.c++',
'semester.c++',
'einschreibung.c++',
'fach.c++',
]

programm_name = 'namen'            # hier Programmnamen festlegen
std.Program(programm_name, cpp_dateien) # Programm bauen
